
const backendDomain="https://ecommerce-s5hw.onrender.com"
const summaryAPI={
     signup:{
         url:`${backendDomain}/api/signup`,
         method:"post"
     },
     login:
     {
        url:`${backendDomain}/api/login`,
        method:"get"
     },
     verified:
     {
        url:`${backendDomain}/api/verified`
     },
     users:
     {
      url:`${backendDomain}/api/users`
     },
     updateuser:
     {
        url:`${backendDomain}/api/updateuser`
     },
     uploadproduct:
     {
      url:`${backendDomain}/api/uploadproduct`
     },
     getproduct:
     {
      url:`${backendDomain}/api/getproduct`
     },
     updateproduct:
     {
      url:`${backendDomain}/api/updateproduct`
     },
     categoryproduct:
     {
     url:`${backendDomain}/api/categoryproduct`
     },
     categorywise:
     {
      url:`${backendDomain}/api/categorywise`
     },
     productdetail:
     {
      url:`${backendDomain}/api/productdetail`
     }
}
export default summaryAPI;
